LinksUseHttps: true
MirrorResources: true
EditLink: => "https://github.com/LuzFaltex/luzfaltex.com/blob/main/input/" + doc.Source.GetRelativeInputPath()
GatherHeadingsLevel: 3
OpenGraphDescription: "Redefining Roleplay"
# Host: Configured in Program.cs